version: '3.7'
services:
    auth:
        build:
            context: ./auth
        environment:
            AUTH_PORT: 3334
        volumes:
            - "./auth/:/mnt"
            - "./proto/:/mnt/proto"
        working_dir: /mnt
        networks:
            - main
    frontend:
        build:
            context: ./frontend
        environment:
            AUTH_HOST: localhost
            AUTH_PORT: 3334
            AUTH_SCHEME: http
            BACKEND_GQL_PATH: /graphql
            BACKEND_HOST: localhost
            BACKEND_PORT: 3333
            BACKEND_SCHEME: http
            FRONTEND_PORT: 8888
        depends_on:
            - "backend"
        volumes:
            - "./frontend:/mnt"
            - "./schema/:/mnt/schema"
            - "./proto/:/mnt/proto"
        working_dir: /mnt
        networks:
            - main
    backend:
        build:
            context: ./backend
        environment:
            BACKEND_GQL_PATH: /graphql
            BACKEND_PLAYGROUND_PATH: /playground
            BACKEND_PORT: 3333
            BACKEND_POSTGRES_DEBUG: 'TRUE'
            BACKEND_SCHEME: http
            MIGRATION_FILEPATH: /mnt/db/migrations
            POSTGRES_DB: pg
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pass
            POSTGRES_HOST: envoy
            POSTGRES_PORT: 5432
            POSTGRES_SCHEMA: public
        volumes:
            - "./backend/:/mnt"
            - "./schema/:/mnt/schema"
        working_dir: /mnt
        networks:
            - main
    envoy:
        build:
            context: ./envoy
        ports:
            - "3333:3333"
            - "3334:3334"
            - "5432:5432"
            - "8888:8888"
            - "9901:9901"
            - "10000:10000"
        volumes:
            - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
            - ./envoy/cfg:/mnt/cfg
        networks:
            - main
    postgres:
        build:
          context: ./postgres
        restart: always
        environment:
            POSTGRES_DB: pg
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pass
            POSTGRES_PORT: 5432
            POSTGRES_SCHEMA: public
        volumes:
            - "pg_data:/var/lib/postgresql/data"
        networks:
            - main

volumes:
    pg_data:

networks:
    main:
        name: stack-net
        driver: bridge